<a href="https://colab.research.google.com/github/bentosilva/nlp-in-python-tutorial/blob/master/nlp_in_action.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

sentence = "Thomas Jefferson began building Monticello at the age of 26."
print(sentence.split())

token_sequence = str.split(sentence)
vocab = sorted(set(token_sequence))
num_tokens = len(token_sequence)
vocab_size = len(vocab)

onehot_vectors = np.zeros((num_tokens, vocab_size), int)
print(onehot_vectors)

L = ['apples', 'bananas', 'oranges']
for i, val in enumerate(L):
  print("i is %d and val is %s" % (i, val))

for i, word in enumerate(token_sequence):
  onehot_vectors[i, vocab.index(word)] = 1
print(' '.join(vocab))





['Thomas', 'Jefferson', 'began', 'building', 'Monticello', 'at', 'the', 'age', 'of', '26.']
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
i is 0 and val is apples
i is 1 and val is bananas
i is 2 and val is oranges
26. Jefferson Monticello Thomas age at began building of the
